# Generated by Django 5.2.14 on 2026-06-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='img_public_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
