# Generated by Django 5.2.14 on 2026-06-02 04:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_test_img_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='img_public_id',
        ),
        migrations.AlterField(
            model_name='test',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
