# Generated by Django 5.2.14 on 2026-06-02 04:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_remove_test_img_public_id_alter_test_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
