# Generated by Django 5.2.14 on 2026-06-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_test_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='img',
            new_name='poster',
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
