# Generated by Django 5.2.14 on 2026-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_rename_img_test_poster_alter_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='short_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
