# Generated by Django 5.2.14 on 2026-06-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_doctor_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.JSONField(default=list),
        ),
    ]
