# Generated by Django 5.2.14 on 2026-06-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_doctor_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(default=7, max_length=2),
            preserve_default=False,
        ),
    ]
