# Generated by Django 5.2.14 on 2026-06-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_alter_doctor_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
