# Generated by Django 5.2.14 on 2026-06-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_alter_doctor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
