# Generated by Django 5.2.14 on 2026-07-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='DOB',
            field=models.DateField(blank=True, default="1998-02-06"),
            preserve_default=False,
        ),
    ]
