# Generated by Django 5.2.14 on 2026-07-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='verification_status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
