# Generated by Django 5.2.14 on 2026-07-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_doctor_verification_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='education',
            new_name='education_and_experience',
        ),
    ]
