import { useEffect, useState } from "react";
import AppointmentTabs from "./appointments/appointment-tabs";
import AppointmentFilterAndSearch from "./appointments/filter-search";
import InfoCards from "./appointments/info-cards";
import type { Appointment } from "./interface/interface";
import { useAuthStore } from "@/zustand/auth";
import { getAppointmentsByPatient } from "@/api/appointment";
import { useHospitalStore } from "@/zustand/hospital";

const History = () => {
  // const Appointments = [
  //   {
  //     id: 38,
  //     reason: "as",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-38",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "CONFIRMED",
  //     date: "2026-06-14",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 39,
  //     reason: "wq",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-39",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 9,
  //         test: "Treadmill Test",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "PENDING",
  //     date: "2026-06-14",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 40,
  //     reason: "wsd",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-40",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 9,
  //         test: "Treadmill Test",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "PENDING",
  //     date: "2026-06-14",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 41,
  //     reason: "hgaf",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-41",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 9,
  //         test: "Treadmill Test",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "CONFIRMED",
  //     date: "2026-06-14",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 42,
  //     reason: "faaf",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-42",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-14",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 43,
  //     reason: "wer",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-43",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "CANCELLED",
  //     date: "2026-06-14",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 44,
  //     reason: "hjahs",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-44",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 9,
  //         test: "Treadmill Test",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-14",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 45,
  //     reason: "ytf6y",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-45",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //       {
  //         id: 9,
  //         test: "Treadmill Test",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-14",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 46,
  //     reason: "as",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-46",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-14",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 47,
  //     reason: "agjs",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-47",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-14",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 48,
  //     reason: "gshs",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-48",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-14",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 49,
  //     reason: "ssss",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-49",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "CANCELLED",
  //     date: "2026-06-14",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 50,
  //     reason: "qywu",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-50",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //       {
  //         id: 9,
  //         test: "Treadmill Test",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-14",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 51,
  //     reason: "jksdbkus",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-51",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //       {
  //         id: 9,
  //         test: "Treadmill Test",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-14",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 52,
  //     reason: "hdkdhd",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-52",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-14",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 53,
  //     reason: "uyafs",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-53",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 9,
  //         test: "Treadmill Test",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-14",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 54,
  //     reason: "Regular Check-up post CABG",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-JZEALP-MJAAI",
  //     symptoms: [],
  //     patient: 4,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-10",
  //     time: "11:30:00",
  //   },
  //   {
  //     id: 55,
  //     reason: "Regular Check-up post CABG",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-91400079-732",
  //     symptoms: [],
  //     patient: 4,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-10",
  //     time: "11:30:00",
  //   },
  //   {
  //     id: 56,
  //     reason: "Regular Check-up post CABG",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-19319315-397",
  //     symptoms: [],
  //     patient: 4,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "CANCELLED",
  //     date: "2026-06-10",
  //     time: "11:30:00",
  //   },
  //   {
  //     id: 57,
  //     reason: "hey",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-52873422-355",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 9,
  //         test: "Treadmill Test",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-18",
  //     time: "11:00:00",
  //   },
  //   {
  //     id: 58,
  //     reason: "haga",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-20869231-039",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 9,
  //         test: "Treadmill Test",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 59,
  //     reason: "haga",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-73156879-046",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //       {
  //         id: 10,
  //         test: "MRI Scan",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 60,
  //     reason: "as",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-39753826-078",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //       {
  //         id: 9,
  //         test: "Treadmill Test",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 61,
  //     reason: "af",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-85560078-819",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 9,
  //         test: "Treadmill Test",
  //       },
  //       {
  //         id: 10,
  //         test: "MRI Scan",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 62,
  //     reason: "gsgs",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-28060907-512",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 9,
  //         test: "Treadmill Test",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 63,
  //     reason: "aas",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-06644030-942",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 64,
  //     reason: "ahgs",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-50911277-380",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 65,
  //     reason: "bhu",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-94875092-338",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 66,
  //     reason: "asas",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-76324649-324",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 67,
  //     reason: "dds",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-28882634-011",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 68,
  //     reason: "Regular Check-up post CABG",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-07496670-279",
  //     symptoms: [],
  //     patient: 4,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-10",
  //     time: "11:30:00",
  //   },
  //   {
  //     id: 69,
  //     reason: "ass",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-76552654-394",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 70,
  //     reason: "aa",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-86505282-261",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 71,
  //     reason: "aaa",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-70587947-258",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 72,
  //     reason: "aaaaa",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-46068459-208",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 9,
  //         test: "Treadmill Test",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 73,
  //     reason: "aa",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-99726385-335",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 74,
  //     reason: "aaa",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-87708913-796",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 10,
  //         test: "MRI Scan",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 75,
  //     reason: "aaaa",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-65602696-293",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 76,
  //     reason: "aaaa",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-77139006-645",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 77,
  //     reason: "hjj",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-64622945-431",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 78,
  //     reason: "jj",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-65654970-844",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 10,
  //         test: "MRI Scan",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 79,
  //     reason: "gaha",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-82508761-723",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 80,
  //     reason: "aaa",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-59131285-956",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 81,
  //     reason: "ahaha",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-86908861-483",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 82,
  //     reason: "aaa",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-53069442-529",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 83,
  //     reason: "aaa",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-04867632-149",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 84,
  //     reason: "aaa",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-98362457-780",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 85,
  //     reason: "aa",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-90729155-294",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 86,
  //     reason: "Regular Check-Up, 6 months once, Post-CABG.",
  //     appointment_type: "Home Visit",
  //     appointment_code: "APT-13176408-364",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //       {
  //         id: 9,
  //         test: "Treadmill Test",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-12-08",
  //     time: "11:00:00",
  //   },
  //   {
  //     id: 87,
  //     reason: "hjshjsjs",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-70047380-364",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //       {
  //         id: 8,
  //         test: "Electrocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-15",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 88,
  //     reason: "hags",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-69509534-178",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-24",
  //     time: "10:00:00",
  //   },
  //   {
  //     id: 89,
  //     reason: "hagaha",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-88107826-720",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-30",
  //     time: "11:00:00",
  //   },
  //   {
  //     id: 90,
  //     reason: "g",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-09588760-866",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-22",
  //     time: "11:00:00",
  //   },
  //   {
  //     id: 91,
  //     reason: "a",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-04916958-320",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-23",
  //     time: "11:00:00",
  //   },
  //   {
  //     id: 92,
  //     reason: "hajs",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-96444664-555",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 10,
  //         test: "MRI Scan",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-30",
  //     time: "11:45:00",
  //   },
  //   {
  //     id: 93,
  //     reason: "hajsl",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-44033849-409",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-30",
  //     time: "11:45:00",
  //   },
  //   {
  //     id: 94,
  //     reason: "jka",
  //     appointment_type: "Clinic",
  //     appointment_code: "APT-34748623-704",
  //     symptoms: [""],
  //     patient: 1,
  //     doctor: {
  //       id: 1,
  //       user: {
  //         id: 6,
  //         first_name: "Thejaswi",
  //         last_name: "N Marla",
  //         username: "@Dr_Thejaswi",
  //         profile_img: "image/upload/v1782148232/tjndobcpu8fc0lvftncr.jpg",
  //         email: "thejaswi@gmail.com",
  //         phone: "7667662174",
  //         role: "DOCTOR",
  //         is_staff: false,
  //         is_verified: true,
  //       },
  //       specialization: {
  //         id: 1,
  //         name: "Cardiologist",
  //         description:
  //           "A cardiologist is a specialized physician who diagnoses, treats, and prevents diseases of the heart and blood vessels.",
  //       },
  //       department: {
  //         id: 1,
  //         name: "Cardiology",
  //       },
  //       education: [
  //         "MBBS",
  //         "MS - General Surgery",
  //         "MCh - Cardio Thoracic and Vascular Surgery",
  //       ],
  //       experience: 18,
  //       location: "",
  //       languages: ["English", "Tamil", "Hindi"],
  //       consultation_fee: "1000.00",
  //       availability: true,
  //       rating: "5.0",
  //     },
  //     tests: [
  //       {
  //         id: 7,
  //         test: "Echocardiogram",
  //       },
  //     ],
  //     status: "COMPLETED",
  //     date: "2026-06-30",
  //     time: "11:45:00",
  //   },
  // ];
  const [appointments, setAppointments] = useState<Appointment[]>([]);
  const { user } = useAuthStore();
  const [id, setId] = useState();
  const { doctor, patient } = useHospitalStore();

  console.log('====================================');
  console.log(patient);
  console.log('====================================');
  // if (user?.role === "DOCTOR") {
  //   setId(doctor?.id);
  // } else if (user?.role === "PATIENT") {
  //   setId(patient?.id);
  // }
  // const isAdmin = user?.role === "ADMIN";
  useEffect(() => {
    const getAppointments = async () => {
      if (user?.role === "DOCTOR") {
        const data = await getAppointmentsByPatient(doctor?.id);
        setAppointments(data);
      } else if (user?.role === "PATIENT") {
        const data = await getAppointmentsByPatient(patient?.id);
        setAppointments(data);
      }
    };

    getAppointments();
  }, []);

  return (
    <>
      <InfoCards appointments={appointments} />
      <AppointmentFilterAndSearch />
      <AppointmentTabs appointments={appointments} />
    </>
  );
};

export default History;
