# Generated by Django 5.2.14 on 2026-06-02 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profiel_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profiel_img',
            new_name='profile_img',
        ),
    ]
