# Generated by Django 5.2.14 on 2026-06-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetail',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billingdetail',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billingdetail',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billingdetail',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Card', 'Card'), ('NEFT', 'NEFT'), ('Cash', 'Cash')], max_length=20, null=True),
        ),
    ]
