# Generated by Django 5.2.14 on 2026-06-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_billingdetail_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('discount', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.AddField(
            model_name='billingdetail',
            name='discount_code',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
