# Generated by Django 5.2.14 on 2026-06-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_discounts_billingdetail_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetail',
            name='discount_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='code',
            field=models.CharField(max_length=16),
        ),
    ]
