# Generated by Django 5.2.14 on 2026-06-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_billingdetail_discount_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetail',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
