# Generated by Django 5.2.14 on 2026-06-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_billingdetail_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetail',
            name='discount_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
