# Generated by Django 5.2.14 on 2026-05-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medications', models.JSONField(default=list, null=True)),
                ('diagnoses', models.JSONField(default=list, null=True)),
                ('allergies', models.JSONField(default=list, null=True)),
                ('treatment_history', models.CharField(blank=True, max_length=255, null=True)),
                ('surgery_history', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
