# Generated by Django 5.2.14 on 2026-06-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_medicalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='tests',
            field=models.JSONField(null=True),
        ),
    ]
