# Generated by Django 5.2.14 on 2026-06-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_medicalreport_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='allergies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnoses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='medications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='prescription',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='tests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='vitals',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
