# Generated by Django 5.2.14 on 2026-06-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
