# Generated by Django 5.2.14 on 2026-06-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_tests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='title',
            new_name='reason',
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
