# Generated by Django 5.2.14 on 2026-06-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_rename_title_appointment_reason_appointment_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(),
        ),
    ]
