# Generated by Django 5.2.14 on 2026-06-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_appointment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('Clinic', 'Clinic'), ('Video Call', 'Video Call'), ('Audio Call', 'Audio Call'), ('Chat', 'Chat'), ('Home Visit', 'Home Visit')], default='Clinic', max_length=20),
        ),
    ]
