# Generated by Django 5.2.14 on 2026-06-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_appointment_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_code',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
