# Generated by Django 5.2.14 on 2026-06-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_appointment_appointment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_code',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
