# Generated by Django 5.2.14 on 2026-06-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_alter_appointment_appointment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='life_style_habits',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
