# Generated by Django 5.2.14 on 2026-06-23 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_medicalrecord_life_style_habits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Mod', 'Mod'), ('High', 'High')], default='Mod', max_length=4)),
                ('management', models.CharField(max_length=100)),
                ('medication', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LifeStyleHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoking', models.CharField(max_length=100)),
                ('alcohol', models.CharField(max_length=100)),
                ('exercise', models.CharField(max_length=100)),
                ('diet', models.CharField(max_length=100)),
                ('sleep', models.CharField(max_length=100)),
                ('medication', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('since', models.CharField(max_length=4)),
                ('management', models.CharField(max_length=100)),
                ('medication', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='diagnoses',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='surgery_history',
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='life_style_habits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_style_habits', to='appointment.lifestylehabit'),
        ),
    ]
