# Generated by Django 5.2.14 on 2026-06-23 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_allergy_lifestylehabit_medicalcondition_surgery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor',
        ),
    ]
