# Generated by Django 5.2.14 on 2026-06-23 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_remove_medicalrecord_doctor'),
        ('hospital', '0018_alter_doctor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='hospital.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lifestylehabit',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='life_style_habits', to='hospital.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalcondition',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medical_condition', to='hospital.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surgery',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='surgery', to='hospital.patient'),
            preserve_default=False,
        ),
    ]
