# Generated by Django 5.2.14 on 2026-06-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_allergy_patient_lifestylehabit_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy',
            old_name='management',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='medication',
        ),
    ]
