# Generated by Django 5.2.14 on 2026-06-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_rename_management_allergy_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy',
            old_name='name',
            new_name='allergy',
        ),
        migrations.RenameField(
            model_name='medicalcondition',
            old_name='name',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='surgery',
            old_name='name',
            new_name='surgery',
        ),
        migrations.RemoveField(
            model_name='lifestylehabit',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='lifestylehabit',
            name='medication',
        ),
        migrations.AddField(
            model_name='lifestylehabit',
            name='activity',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lifestylehabit',
            name='taking_medication',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surgery',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lifestylehabit',
            name='alcohol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lifestylehabit',
            name='sleep',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lifestylehabit',
            name='smoking',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
