# Generated by Django 5.2.14 on 2026-06-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_rename_name_allergy_allergy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalreport',
            old_name='tests',
            new_name='diagnosis_and_findings',
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='type',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
