# Generated by Django 5.2.14 on 2026-06-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0018_rename_tests_medicalreport_diagnosis_and_findings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='follow_up',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
