# Generated by Django 5.2.14 on 2026-06-27 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0019_medicalreport_follow_up_medicalreport_title'),
        ('hospital', '0018_alter_doctor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcondition',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_conditions', to='hospital.patient'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='hospital.patient'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_reports', to='appointment.appointment'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='hospital.patient'),
        ),
    ]
