# Generated by Django 5.2.14 on 2026-07-01 18:56

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0020_alter_medicalcondition_patient_and_more'),
        ('hospital', '0019_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='vitals',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='diagnosis_and_findings',
        ),
        migrations.CreateModel(
            name='ImagingReport',
            fields=[
                ('medicalreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointment.medicalreport')),
                ('scan', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('findings', models.TextField()),
                ('impression', models.TextField()),
            ],
            bases=('appointment.medicalreport',),
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('medicalreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointment.medicalreport')),
                ('tests', models.JSONField(blank=True, default=list)),
                ('lab_notes', models.TextField()),
                ('doctor_notes', models.TextField()),
            ],
            bases=('appointment.medicalreport',),
        ),
        migrations.CreateModel(
            name='SurgeryReport',
            fields=[
                ('medicalreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointment.medicalreport')),
                ('surgery_name', models.CharField(max_length=100)),
                ('surgeon_notes', models.TextField()),
            ],
            bases=('appointment.medicalreport',),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_reports', to='appointment.appointment'),
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='doctor',
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='hospital.patient')),
            ],
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='doctor',
            field=models.ManyToManyField(blank=True, related_name='medical_reports', to='hospital.doctor'),
        ),
        migrations.CreateModel(
            name='AppointmentReport',
            fields=[
                ('medicalreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointment.medicalreport')),
                ('notes', models.TextField()),
                ('prescription', models.JSONField(blank=True, default=list)),
                ('diagnosis_and_findings', models.JSONField(blank=True, default=list)),
                ('vitals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals', to='appointment.vitals')),
            ],
            bases=('appointment.medicalreport',),
        ),
    ]
