# Generated by Django 5.2.14 on 2026-07-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0021_remove_medicalreport_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='lab_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='doctor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='lab_notes',
            field=models.TextField(blank=True),
        ),
    ]
