# Generated by Django 5.2.14 on 2026-07-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0022_labreport_lab_details_alter_labreport_doctor_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentreport',
            name='vitals',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
