# Generated by Django 5.2.14 on 2026-07-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0023_alter_appointmentreport_vitals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Mod', max_length=8),
        ),
    ]
