# Generated by Django 5.2.14 on 2026-07-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0024_alter_allergy_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='status',
            field=models.CharField(default="Normal", max_length=20),
            preserve_default=False,
        ),
    ]
