# Generated by Django 5.2.14 on 2026-07-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0025_medicalreport_status'),
    ]

    operations = [
    ]
